apiVersion: v1
kind: Service
metadata:
  name: springboot-pr7-service
spec:
  type: NodePort
  selector:
    app: springboot-pr7
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
